name: Update Quote Readme

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - master

jobs:
  update-readme:
    name: Update Quote README
    runs-on: ubuntu-latest
    steps:
      - uses: siddharth2016/quote-readme@main
        with:
          COMMIT_MESSAGE: Added today's fact       # default - Update with quote-readme
          OPTION: funfact # default - both, can be one of (quote, funfact, both), if 'both' then will display either a quote or a fact
